export const queryKeys = {
    sessions: ['sessions'] as const,
    session: (sessionId: string) => ['session', sessionId] as const,
    messages: (sessionId: string) => ['messages', sessionId] as const,
    machines: ['machines'] as const,
    shares: (baseUrl: string, namespace: string) => ['shares', baseUrl, namespace] as const,
    monitors: ['monitors'] as const,
    monitor: (monitorId: string) => ['monitor', monitorId] as const,
    machineCodexModels: (machineId: string) => ['machine-codex-models', machineId] as const,
    machineCodexSubscriptionLimits: (machineId: string, model: string | null) => [
        'machine-codex-subscription-limits',
        machineId,
        model
    ] as const,
    gitStatus: (sessionId: string) => ['git-status', sessionId] as const,
    gitBranch: (sessionId: string) => ['git-branch', sessionId] as const,
    machineGitBranch: (machineId: string, cwd: string) => ['machine-git-branch', machineId, cwd] as const,
    machineGitBranches: (machineId: string, cwd: string) => ['machine-git-branches', machineId, cwd] as const,
    sessionFiles: (sessionId: string, query: string) => ['session-files', sessionId, query] as const,
    sessionDirectory: (sessionId: string, path: string) => ['session-directory', sessionId, path] as const,
    sessionFile: (sessionId: string, path: string) => ['session-file', sessionId, path] as const,
    sessionFileBlob: (sessionId: string, path: string) => ['session-file-blob', sessionId, path] as const,
    gitFileDiff: (sessionId: string, path: string, staged?: boolean) => [
        'git-file-diff',
        sessionId,
        path,
        staged ? 'staged' : 'unstaged'
    ] as const,
    slashCommands: (sessionId: string) => ['slash-commands', sessionId] as const,
    sessionCodexModels: (sessionId: string) => ['session-codex-models', sessionId] as const,
    sessionCodexSubscriptionLimits: (sessionId: string, model: string | null) => ['session-codex-subscription-limits', sessionId, model] as const,
    sessionCursorModels: (sessionId: string) => ['session-cursor-models', sessionId] as const,
    sessionPiModels: (sessionId: string) => ['session-pi-models', sessionId] as const,
    machineCursorModels: (machineId: string) => ['machine-cursor-models', machineId] as const,
    sessionOpencodeModels: (sessionId: string) => ['session-opencode-models', sessionId] as const,
    sessionOpencodeReasoningEffortOptions: (sessionId: string) => ['session-opencode-reasoning-effort-options', sessionId] as const,
    codexSessionContext: (machineId: string, sessionId: string) => ['codex-session-context', machineId, sessionId] as const,
    codexSessionFile: (machineId: string, sessionId: string, path: string) => ['codex-session-file', machineId, sessionId, path] as const,
    codexSessionSnapshot: (machineId: string, sessionId: string) => ['codex-session-snapshot', machineId, sessionId] as const,
    codexSessionStatus: (machineId: string, sessionId: string) => ['codex-session-status', machineId, sessionId] as const,
    codexSessionComposerCapabilities: (machineId: string, sessionId: string) => ['codex-session-composer-capabilities', machineId, sessionId] as const,
    machineOpencodeModelsForCwd: (machineId: string, cwd: string) => ['machine-opencode-models', machineId, cwd] as const,
    skills: (sessionId: string) => ['skills', sessionId] as const,
}
