import { readFile, readdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import type { ManagedSkillDefinition } from '@hapi/protocol'
import { loadManagedSkillBundle } from '../src/managedSkillBundles'

const scriptDirectory = dirname(fileURLToPath(import.meta.url))
const hubRoot = join(scriptDirectory, '..')
const skillsRoot = join(hubRoot, 'skills')
const outputPath = join(hubRoot, 'src', 'managedSkillCatalog.generated.ts')

async function loadLibrary(): Promise<ManagedSkillDefinition[]> {
    const library: ManagedSkillDefinition[] = []
    for (const entry of await readdir(skillsRoot, { withFileTypes: true })) {
        if (!entry.isDirectory()) throw new Error(`Only Skill directories are allowed under hub/skills: ${entry.name}`)
        library.push(await loadManagedSkillBundle(join(skillsRoot, entry.name)))
    }
    return library.sort((left, right) => left.id < right.id ? -1 : left.id > right.id ? 1 : 0)
}

function render(library: ManagedSkillDefinition[]): string {
    return [
        '// Generated by hub/scripts/generate-managed-skill-library.ts. Do not edit.',
        "import type { ManagedSkillDefinition } from '@hapi/protocol'",
        '',
        `export const MANAGED_SKILL_LIBRARY: readonly ManagedSkillDefinition[] = ${JSON.stringify(library, null, 4)}`,
        ''
    ].join('\n')
}

async function main(): Promise<void> {
    const expected = render(await loadLibrary())
    if (process.argv.includes('--check')) {
        const current = await readFile(outputPath, 'utf8').catch(() => '')
        if (current !== expected) throw new Error('Managed Skill catalog is stale. Run `bun run generate:managed-skills` in hub/.')
        console.log('Managed Skill catalog is current.')
        return
    }
    await writeFile(outputPath, expected, 'utf8')
    console.log(`Generated ${outputPath}`)
}

main().catch((error) => {
    console.error(error instanceof Error ? error.message : String(error))
    process.exit(1)
})
