import { expect, test } from '@playwright/test'
import { createDefaultMonitorConfig } from '../web/src/monitoring/presentation'

test.use({ viewport: { width: 375, height: 812 }, isMobile: true, hasTouch: true, deviceScaleFactor: 1 })

test.beforeEach(async ({ page }) => {
    await page.route(url => url.pathname.startsWith('/api/'), async route => {
        const path = new URL(route.request().url()).pathname
        if (path === '/api/machines') return route.fulfill({ json: { machines: [{ id: 'fixture-machine', active: true, metadata: { host: 'Test Mac', workspaceRoots: ['/workspace'] } }] } })
        if (path === '/api/sessions') return route.fulfill({ json: { sessions: [] } })
        if (path.endsWith('/paths/exists')) return route.fulfill({ json: { exists: {} } })
        if (path.endsWith('/codex-models')) return route.fulfill({ json: { success: true, models: [{ id: 'gpt-fixture', displayName: 'GPT Fixture', supportedReasoningEfforts: ['low', 'high'] }] } })
        if (path.endsWith('/list-directory')) return route.fulfill({ json: { success: true, entries: [{ name: 'api', type: 'directory' }], path: '/workspace' } })
        return route.fulfill({ status: 404, json: { error: 'Unmocked fixture request' } })
    })
})

test('new session selects its directory in place and preserves model and reasoning', async ({ page }) => {
    await page.goto('/e2e-fixtures/monitor-form-fixture.html?newSession=1')
    const models = page.locator('select').filter({ has: page.locator('option[value="gpt-fixture"]') })
    await models.selectOption('gpt-fixture')
    const reasoning = page.locator('select').filter({ has: page.locator('option[value="high"]') })
    await reasoning.selectOption('high')
    const url = page.url()
    await page.getByRole('button', { name: 'Browse', exact: true }).click()
    await expect(page.getByRole('dialog')).toBeVisible()
    await page.getByRole('button', { name: 'Use this directory', exact: true }).click()
    await expect(page.getByRole('dialog')).toHaveCount(0)
    expect(page.url()).toBe(url)
    await expect(page.locator('input[type="text"]').first()).toHaveValue('/workspace')
    await expect(models).toHaveValue('gpt-fixture')
    await expect(reasoning).toHaveValue('high')
})

test('mobile monitor mode tabs and scheduled form fit without horizontal overflow', async ({ page }, info) => {
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    await page.goto('/e2e-fixtures/monitor-form-fixture.html')
    await expect(page.getByRole('radio', { name: 'Probe', exact: true })).toBeAttached()
    await page.getByText('Scheduled', { exact: true }).click()
    await expect(page.getByRole('radio', { name: 'Scheduled', exact: true })).toBeChecked()
    await expect(page.getByRole('radio', { name: 'Probe', exact: true })).not.toBeChecked()
    await expect(page.locator('input[type="time"]')).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await page.screenshot({ path: info.outputPath('monitor-scheduled-375.png'), fullPage: true, animations: 'disabled' })
    expect(errors).toEqual([])
})

test('monitor card supports enable switch and swipe reveal without passive uptime text', async ({ page }, info) => {
    await page.goto('/e2e-fixtures/monitor-form-fixture.html?card=1')
    const enabled = page.getByRole('switch', { name: 'Enabled', exact: true })
    await expect(enabled).toBeChecked()
    await page.getByText('Enabled', { exact: true }).click()
    await expect(enabled).not.toBeChecked()
    await expect(page.getByText(/uptime|online rate/i)).toHaveCount(0)
    const card = page.locator('[data-monitor-swipe]')
    await expect(page.getByRole('button', { name: 'Delete', exact: true })).toHaveCount(0)
    await expect(card.locator('button[aria-label="Delete"]')).toHaveCount(1)
    const box = (await card.boundingBox())!
    await page.mouse.move(box.x + box.width - 45, box.y + 35)
    await page.mouse.down()
    await page.mouse.move(box.x + box.width - 140, box.y + 35, { steps: 12 })
    await page.mouse.up()
    await expect(card.locator(':scope > div')).toHaveCSS('transform', 'matrix(1, 0, 0, 1, -80, 0)')
    await page.screenshot({ path: info.outputPath('monitor-swipe-375.png'), animations: 'disabled' })
    await card.locator(':scope > button').click()
    await expect(page.getByText('delete requested')).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
})

test('monitor detail groups passive metrics and settings on mobile and landscape', async ({ page }, info) => {
    await page.route('**/api/monitors/fixture', route => route.fulfill({ json: { monitor: {
        id: 'fixture', config: { ...createDefaultMonitorConfig(), kind: 'webhook', name: 'Production events', machineId: 'fixture-machine', directory: '/workspace/api' },
        health: 'unknown', createdAt: Date.now(), updatedAt: Date.now(), lastCheckedAt: Date.now(), lastLatencyMs: null, lastError: null, buckets: [], incident: null, incidents: []
    } } }))
    await page.goto('/e2e-fixtures/monitor-form-fixture.html?detail=1')
    await expect(page.getByRole('heading', { name: 'Production events' })).toBeVisible()
    await expect(page.getByText('Last triggered', { exact: true })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: info.outputPath('monitor-detail-375.png') })
    await page.getByRole('tab', { name: 'Configuration' }).click()
    const enabled = page.getByRole('switch', { name: 'Enabled', exact: true })
    const notifications = page.getByRole('switch', { name: 'Push notifications', exact: true })
    await enabled.locator('..').scrollIntoViewIfNeeded()
    await expect(page.getByText('Push notifications', { exact: true })).toBeInViewport()
    const left = await enabled.locator('..').boundingBox(), right = await notifications.locator('..').boundingBox()
    expect(Math.abs(left!.y - right!.y)).toBeLessThan(2)
    expect(left!.x + left!.width).toBeLessThanOrEqual(right!.x)
    await page.screenshot({ path: info.outputPath('monitor-settings-375.png') })
    await page.emulateMedia({ reducedMotion: 'reduce', colorScheme: 'dark' })
    await page.evaluate(() => { document.documentElement.dataset.theme = 'dark'; document.documentElement.classList.add('dark') })
    await page.setViewportSize({ width: 812, height: 375 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: info.outputPath('monitor-settings-landscape.png') })
})

test('bound monitor hides environment controls and saves exact source binding', async ({ page }, info) => {
    await page.goto('/e2e-fixtures/monitor-form-fixture.html?bound=1')
    await page.getByText('Webhook', { exact: true }).click()
    await expect(page.getByText('/workspace/api', { exact: true })).toHaveCount(0)
    const notificationSwitch = page.getByRole('switch', { name: 'Push notifications', exact: true })
    await expect(notificationSwitch).toBeChecked()
    await page.getByText('Push notifications', { exact: true }).click()
    await expect(notificationSwitch).not.toBeChecked()
    await page.getByRole('button', { name: 'Save fixture' }).click()
    const config = JSON.parse(await page.getByTestId('saved-config').textContent() || '{}')
    expect(config.targetSession).toEqual({ type: 'native-codex', sessionId: 'fixture-session' })
    expect(config.kind).toBe('webhook')
    expect(config.notificationsEnabled).toBe(false)
    expect(config.machineId).toBe('fixture-machine')
    await page.evaluate(() => window.scrollTo(0, 0))
    await page.screenshot({ path: info.outputPath('monitor-bound-375.png'), fullPage: true })
})

test('offers real model choices, recent directories and a directory drawer without creating a session', async ({ page }, info) => {
    await page.addInitScript(() => localStorage.setItem('hapi:recentPaths', JSON.stringify({ 'fixture-machine': ['/workspace/recent'] })))
    await page.goto('/e2e-fixtures/monitor-form-fixture.html')
    await page.getByText('Webhook', { exact: true }).click()
    const models = page.locator('select').filter({ has: page.locator('option[value="gpt-fixture"]') })
    await models.selectOption('gpt-fixture')
    const reasoning = page.locator('select').filter({ has: page.locator('option[value="ultra"]') })
    await reasoning.selectOption('high')
    await page.getByText('/workspace/recent', { exact: true }).click()
    await expect(page.getByRole('textbox', { name: /^Project directory/ })).toHaveValue('/workspace/recent')
    await page.getByRole('button', { name: 'Browse', exact: true }).click()
    await expect(page.getByRole('dialog')).toBeVisible()
    const drawer = page.getByRole('dialog')
    await expect(drawer).not.toHaveAttribute('aria-describedby', /.+/)
    await expect.poll(async () => {
        const box = await drawer.boundingBox()
        return Math.round(box?.height ?? 0)
    }).toBe(Math.round(812 * 0.7))
    await page.screenshot({ path: info.outputPath('monitor-directory-375.png'), animations: 'disabled' })
    await page.getByRole('button', { name: 'Use this directory', exact: true }).click()
    await expect(page.getByRole('dialog')).toHaveCount(0)
    await page.getByRole('button', { name: 'Save fixture' }).click()
    const config = JSON.parse(await page.getByTestId('saved-config').textContent() || '{}')
    expect(config.model).toBe('gpt-fixture')
    expect(config.reasoningEffort).toBe('high')
    expect(config.directory).toBe('/workspace')
})
